API_KEY = 'PKAYBJPRD4GWS0JWS0HH'
SECRET_KEY = '8nhyGCwGbRrYwuoI1ERsf1RBunAFAkTOLVB3o0ta'
BASE_URL = 'https://paper-api.alpaca.markets'
KEYS = {'APCA-API-KEY-ID': API_KEY, 'APCA-API-SECRET-KEY': SECRET_KEY}